#ifndef SANESCANNERLINUXYUSHULX_GLOBAL_H
#define SANESCANNERLINUXYUSHULX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SANESCANNERLINUXYUSHULX_LIBRARY)
#  define SANESCANNERLINUXYUSHULXSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SANESCANNERLINUXYUSHULXSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SANESCANNERLINUXYUSHULX_GLOBAL_H
